version: "3.1"
services:
  aegis-api:
    build: ./api
    container_name: aegis-api-service
    working_dir: /usr/es-backend-AegisAPI
    volumes:
      - ./:/usr/es-discord-oreonitemanganese
      - /usr/es-discord-oreonitemanganese/node_modules
    ports:
      - ${PORT}:${PORT}
    command: "npm run start"
